os: linux

dist: xenial

language: python

cache: pip

python: 3.8

stages:
  - lint
  - test
  - deploy

jobs:
  include:
    - name: "Linting"
      stage: lint
      before_script:
        - git remote set-branches --add origin master
        - git fetch
      script:
        - export CHANGED_FILES=`git diff --name-only --diff-filter=d origin/master | grep -E '\.py$' | tr '\n' ' '` understatapi/api.py
        - black --check --line-length=79 $CHANGED_FILES
        - pylint $CHANGED_FILES
        - mypy -p understatapi
    - name: "Running unit tests"
      stage: test
    - name: "Updating documentation"
      stage: deploy
      deploy: 
<<<<<<< HEAD
        - provider: pages
          edge: true
          skip_cleanup: true
          github_token: "$GITHUB_TOKEN"
          keep_history: true
          local_dir: docs/build/
=======
        - provider: pages:git
          script: ./make_docs.sh
          edge: true
          verbose: true
          skip_cleanup: true
          github_token: $GITHUB_TOKEN
          keep_history: true
          local_dir: ./docs/build/html
>>>>>>> dev
          on:
            branch: master


install:
  - pip install -r requirements.txt
  - pip install -r test_requirements.txt

script:
  - coverage run -m unittest discover
  - coverage report --fail-under=100