language: python

stages:
  - lint
  - test
  - deploy

jobs:
  include:
    - name: "Linting"
      stage: lint
      python: 3.9
      script:
        - black --check --line-length=79 .
        - pylint understatapi/ test/
        - mypy -p understatapi
    - name: "Python 3.7 testing"
      stage: test
      python: 3.7
    - name: "Python 3.8 testing"
      python: 3.8
    - name: "Python 3.9 testing"
      python: 3.9
    - name: "Deploy"
      install:
        - pip install docs/requirements.txt
        - curl -sfL https://install.goreleaser.com/github.com/ValeLint/vale.sh | sh -s v2.1.0 # install vale
        - export PATH="./bin:$PATH"
      script: sphinx-build -b html docs/ docs/build/ -c docs/
      deploy: 
        provider: pages
        skip_cleanup: true
        github_token: "$GITHUB_TOKEN"
        keep_history: true
        local_dir: docs/build/
        on:
          branch: master


install:
  - pip install -r requirements.txt
  - pip install -r test_requirements.txt

script:
  - coverage run -m unittest discover
  - coverage report --fail-under=100