language: python

cache: pip

stages:
  - lint
  - test
  - deploy

jobs:
  include:
    - name: "Linting"
      stage: lint
      python: 3.9
      script:
        - black --check --line-length=79 understatapi/ test/ setup.py
        - pylint understatapi/ test/
        - mypy -p understatapi
    - name: "Python 3.7 testing"
      stage: test
      python: 3.7
    - name: "Python 3.8 testing"
      python: 3.8
    - name: "Python 3.9 testing"
      python: 3.9
    - name: "Update documentation"
      stage: deploy
      python: 3.9
      install:
        - pip install -r docs/requirements.txt
      script:
        - sphinx-apidoc --separate -f -o docs/source . ./setup.py ./test
        - cd docs && make html
      deploy: 
        - provider: pages
          edge: true
          skip_cleanup: true
          github_token: "$GITHUB_TOKEN"
          keep_history: true
          local_dir: docs/build/
          on:
            branch: master


install:
  - pip install -r requirements.txt
  - pip install -r test_requirements.txt

script:
  - coverage run -m unittest discover
  - coverage report --fail-under=100