language: python

python:
  - "3.7"
  - "3.8"
  - "3.9"

install:
  - pip install -r requirements.txt
  - pip install -r test_requirements.txt

script:
  - black --check --line-length=79 .
  - pylint understatapi/ test/
  - mypy understatapi/
  - coverage run -m unittest discover
  - coverage report --fail-under=100