os: linux

dist: xenial

language: python

cache: pip

python: 3.8

stages:
  - lint
  - test
  - deploy

jobs:
  include:
    - name: "Linting"
      stage: lint
      before_script:
        - git remote set-branches --add origin master
        - git fetch
      script:
        - echo $CHANGED_FILES
        - export CHANGED_FILES=`git diff --name-only --diff-filter=d origin/master | grep -E '\.py$' | tr '\n' ' '`
        - echo $CHANGED_FILES
        - black --check --line-length=79 $CHANGED_FILES
        - pylint $CHANGED_FILES
        - mypy -p understatapi
    - name: "Running unit tests"
      stage: test
    - name: "Updating documentation"
      stage: deploy
      install:
        - pip install -r docs/requirements.txt
      script:
        - sphinx-apidoc --separate -f -o docs/source . ./setup.py ./test
        - cd docs && make html
      deploy: 
        - provider: pages:git
          edge: true
          verbose: true
          skip_cleanup: true
          github_token: $GITHUB_TOKEN
          keep_history: true
          local_dir: ./docs/build/html
          on:
            branch: master


install:
  - pip install -r requirements.txt
  - pip install -r test_requirements.txt

script:
  - coverage run -m unittest discover
  - coverage report --fail-under=100