os: linux
dist: xenial
language: python
cache: pip
python: 3.8

stages:
  - test
  - deploy

jobs:
  include:
    - name: "Testing"
      stage: test
      before_script:
        - git remote set-branches --add origin master
        - git fetch
      script:
        - ./run_tests.sh
    - name: "Deploying"
      stage: deploy
      deploy: 
        - provider: pages:git
          edge: true
          verbose: true
          cleanup: false
          token: $GITHUB_TOKEN
          keep_history: true
          local_dir: ./docs/build/html/
          on:
            branch: master

        - provider: pypi
          edge: true
          username: __token__
          password: $PYPI_TOKEN
          distributions: "sdist"
          skip_existing: true
          on:
            branch: master
            tags: true

        - provider: releases
          edge: true
          token: $GITHUB_TOKEN
          on:
            branch: master
            tags: true


install:
  - pip install -r requirements.txt
  - pip install -r test_requirements.txt
  - pip install -r docs/requirements.txt

script:
  - python setup.py install
  - ./make_docs.sh
